[Added] [BEL-7799] Add support for risk insights endpoint
belvo-finance/belvo-js pull request #111
Opened 2021-11-18 14:58 UTC by jordisoler

- Add support for `/api/risk-insights` endpoint
- Fix recurring expenses test file name

2021-11-18 15:51 UTC, maria-ribalta requested changes

2021-11-18 15:51 UTC, maria-ribalta commented on tests/riskInsights.test.js
> +  "transactions_metrics": {
```suggestion
  "transactions_metrics": {
  "num_transactions_1m": 0,
    "num_transactions_1w": 0,
    "num_transactions_3m": 34,
    "max_incoming_amount_1m": 0,
    "max_incoming_amount_1w": 0,
    "max_incoming_amount_3m": 9789.98,
    "max_outgoing_amount_1m": 0,
    "max_outgoing_amount_1w": 0,
    "max_outgoing_amount_3m": 8646.72,
    "sum_incoming_amount_1m": 0,
    "sum_incoming_amount_1w": 0,
    "sum_incoming_amount_3m": 82305.25,
    "sum_outgoing_amount_1m": 0,
    "sum_outgoing_amount_1w": 0,
    "sum_outgoing_amount_3m": 63914.13,
    "mean_incoming_amount_1m": 0,
    "mean_incoming_amount_1w": 0,
    "mean_incoming_amount_3m": 4331.86,
    "mean_outgoing_amount_1m": 0,
    "mean_outgoing_amount_1w": 0,
    "mean_outgoing_amount_3m": 4260.94,
    "num_incoming_transactions_1m": 0,
    "num_incoming_transactions_1w": 0,
    "num_incoming_transactions_3m": 19,
    "num_outgoing_transactions_1m": 0,
    "num_outgoing_transactions_1w": 0,
    "num_outgoing_transactions_3m": 15
  }
```

2021-11-18 15:51 UTC, maria-ribalta commented on tests/riskInsights.test.js
> +  "transactions_metrics": {
with the ticket I have to merge, there won't be nulls in metrics _1m and _1w

2021-11-18 15:55 UTC, maria-ribalta approved these changes

2021-11-19 09:31 UTC, AlbertMaristany approved these changes

2021-11-19 09:36 UTC, merged