[Added] [BEL-10869] Add support for tax retentions endpoint
belvo-finance/belvo-js pull request #135
Opened 2022-07-26 12:14 UTC by GeoffreyVanderCruyssen

2022-07-26 12:15 UTC, GeoffreyVanderCruyssen commented on tests/taxRetentions.test.js
> +import 'regenerator-runtime/runtime';
I had to add this line specifically to make this test suite work, while nothing is different from the other test files. Not sure why, this is an inconsistency that we should take a look at.

2022-07-26 12:44 UTC, guimarquesbelvo submitted a review, later dismissed

2022-07-26 12:44 UTC, guimarquesbelvo commented on tests/taxRetentions.test.js
> +import 'regenerator-runtime/runtime';
```suggestion
import nock from 'nock'; 
import { APIMocker, newSession } from './fixtures';
import TaxRetentions from '../src/taxRetentions';
```

I tested swapping these lines here in other tests and the same error appears. This should do the fix

2022-07-26 12:54 UTC, GeoffreyVanderCruyssen commented on tests/taxRetentions.test.js
> +import 'regenerator-runtime/runtime';
![image](https://user-images.githubusercontent.com/94360996/181010770-3d409230-9d17-487f-a53d-d040f49b1e6d.png)

2022-07-26 15:29 UTC, sergio-belvo approved these changes
🚀

2022-07-26 15:29 UTC, sergio-belvo commented on tests/taxRetentions.test.js
> +  sender_name: 'Roberto Nunez Batman',
🦇 👨

2022-07-26 15:53 UTC, benitocas88 commented on src/taxRetentions.js
> +   * @param {string} DateFrom - Required date from, format is YYYY-MM-DD
Ey @GeoffreyVanderCruyssen note that params documented must match with function args, in this case `dateFrom` ans `dateTo`

2022-07-26 15:54 UTC, benitocas88 commented on tests/taxRetentions.test.js
> +  sender_name: 'Roberto Nunez Batman',
🦇

2022-07-26 15:58 UTC, benitocas88 approved these changes
Probably out of the scope but in case you want, you can implement and test `notImplementError` (custom throw in js) as we do in belvo-python https://github.com/belvo-finance/belvo-python/blob/master/belvo/resources/tax_retentions.py#L54

2022-07-26 16:08 UTC, GeoffreyVanderCruyssen commented on src/taxRetentions.js
> +   * @param {string} DateFrom - Required date from, format is YYYY-MM-DD
@benitocas88 I just looked at what was in [invoices here](https://github.com/belvo-finance/belvo-js/blob/master/src/invoices.js#L1-L44)

2022-07-27 08:25 UTC, AlbertMaristany requested changes
:muscle: Looking good! Lets add some documentation and move on.

2022-07-27 08:25 UTC, AlbertMaristany commented on src/taxRetentions.js
> +class TaxRetentions extends Resource {
We need some documentation on top of the resource. You can check other resources or ask some help to our docs overlord @dom-techwriter

2022-07-27 13:55 UTC, GeoffreyVanderCruyssen commented on src/taxRetentions.js
> + */
Hi @dom-techwriter , how are you?

2022-07-27 14:07 UTC, blv-dominik commented on src/taxRetentions.js
> +class TaxRetentions extends Resource {
This looks good to me! @AlbertMaristany and @GeoffreyVanderCruyssen

2022-07-27 14:09 UTC, blv-dominik approved these changes
looks good to me from a docs perspective! :)

2022-07-27 14:28 UTC, AlbertMaristany approved these changes

2022-07-27 15:37 UTC, merged