[Added] [BEL-16490] Add Tax Declarations endpoint
belvo-finance/belvo-js pull request #142
Opened 2022-10-11 14:32 UTC by blv-albertmaristany

:question: What
---
- Add Tax Declarations endpoint

:speech_balloon: Why
---
- We are adding support to the tax declarations product

2022-10-11 15:18 UTC, blv-dominik requested changes
Hey @blv-albertmaristany ! Just one small typo and a comment for you :)

2022-10-11 15:18 UTC, blv-dominik commented on src/taxDeclarations.js
> +   * Retrieve tax declarations information from a specific fiscal link.
```suggestion
   * Retrieve tax declaration information for a specific fiscal link.
```

2022-10-11 15:18 UTC, blv-dominik commented on tests/taxDeclarations.test.js
> +const taxDeclaration = {
@blv-albertmaristany I just need to warn you... this schema is going to change soon :(

2022-10-13 08:39 UTC, blv-albertmaristany commented on tests/taxDeclarations.test.js
> +const taxDeclaration = {
This is a mock, so it really doesn't matter. It's just used for testing purposes. Although when we have the definitive one, we can update it just for the sake of parity.

2022-11-15 12:53 UTC, blv-geoffreyvandercruyssen commented on src/belvo.js
> +import TaxDeclaration from './taxDeclarations';
What are we gonna do with naming ([context](https://belvo.slack.com/archives/C010GD789V1/p1668208940716209)), because now we are using a mix of singular and plural

2022-11-15 12:57 UTC, blv-geoffreyvandercruyssen approved these changes

2022-11-15 13:16 UTC, blv-dominik approved these changes
nice!

2022-11-16 08:25 UTC, blv-albertmaristany commented on src/belvo.js
> +import TaxDeclaration from './taxDeclarations';
JS SDK has this unfortunate naming since the beginning, but what is actually important is the exposed method, which must be plural. You can see the class exposition some lines below, which is plural.

2022-11-16 08:25 UTC, merged