[Added][BEL-1544] Function 'list' receive an object and convert like query params
belvo-finance/belvo-js pull request #74
Opened 2021-03-19 16:57 UTC by benitocas88

# Why

- Currently is not possible get data using filter options in node-sdk using `list` function.

# What?
- Allow customers get only data he wants sending parameter options to filter

2021-03-19 22:32 UTC, shekodn reviewed
I left a couple of changes/suggestions. Let me know what you think :)

2021-03-19 22:32 UTC, shekodn commented on src/resources.js
> +    const ep = `${this.#endpoint}${qs}`;
```suggestion
    const endpoint = `${this.#endpoint}${qs}`;
```

2021-03-19 22:32 UTC, shekodn commented on src/resources.js
> +    const result = await this.session.list(ep, stop);
```suggestion
    const result = await this.session.list(endpoint, stop);
```

2021-03-19 22:32 UTC, shekodn commented on src/resources.js
> +      params = stop;
why do we use the variable `stop`? could we just use `limit`?

2021-03-22 15:20 UTC, menecio requested changes
Welcome Beni! I'm missing a test case for the filtering here and I left a comment

2021-03-22 15:20 UTC, menecio commented on src/utils.js
> +
There is no need to build the query parameters by yourself, axios already provides `params` for that, basically what you need to make this https://github.com/belvo-finance/belvo-js/blob/master/src/http.js#L77 able to receive the filters and send them using params.

2021-03-22 16:51 UTC, benitocas88 commented on src/resources.js
> +    if (typeof limit === 'object') {
@menecio what do you think about this case, preventing `limit` override if users send object insted of `limit`:
`client.[resource].list({ amount__gte: 5 })`
If they want use filter the `limit` param would be mandatory?

2021-03-23 20:50 UTC, benitocas88 commented
This is a doc example with the change

![image](https://user-images.githubusercontent.com/2643684/112216374-086d0200-8be7-11eb-979b-582f0beecf87.png)

2021-03-24 19:59 UTC, benitocas88 commented on tests/transactions.test.js
> +test('can list transactions given filters', async () => {
@menecio I wanted to do this test at least for some resource to ensure correct functionality

2021-03-25 16:02 UTC, gingrassia approved these changes

2021-03-29 14:37 UTC, menecio approved these changes

2021-03-30 07:35 UTC, merged