[Changed] [BEL-2580] README.md
belvo-finance/belvo-js pull request #77
Opened 2021-04-14 14:57 UTC by jaume-blv

:question: What
---

Added some compliance checks in the README file.

:speech_balloon: Why
---

 

It is required to meet some security compliance best practices.

2021-04-14 14:59 UTC, anisaoshafi commented on README.md
> +- [ ] There is a ticket associated to each PR.
What about external developers that want to contribute with a pr?

2021-04-14 15:04 UTC, menecio commented on README.md
> +- [ ] There is a ticket associated to each PR.
In this case, the ticket number should refer to a github issue. We will need to add checks for this tho.

2021-04-14 15:05 UTC, menecio requested changes

2021-04-14 15:05 UTC, menecio commented on README.md
> +- [ ] The source code has been coded following the OWASP security best practices (https://owasp.org/www-pdf-archive/OWASP_SCP_Quick_Reference_Guide_v2.pdf).
```suggestion
- [ ] The source code has been coded following [the OWASP security best practices](https://owasp.org/www-pdf-archive/OWASP_SCP_Quick_Reference_Guide_v2.pdf).
```

2021-04-21 10:55 UTC, AlbertMaristany approved these changes

2021-04-22 13:50 UTC, merged