[Added][BEL-2924]Dangerfile PR in blocking mode
belvo-finance/belvo-js pull request #85
Opened 2021-05-31 13:45 UTC by jaume-blv

**What**
Added a workflow to validate PR in blocking mode to do not allow merge.

**Why**
- Force PR titles to contain a Jira ticket ID and a bracket indicating its purpose "Fixed|Added|Changed|Removed|Security|Other".
- Force the PR description to have at least 10 characters

2021-05-31 13:59 UTC, jaume-blv reviewed
LGTM

2021-05-31 14:34 UTC, anisaoshafi commented on Dangerfile
> +	message ("Autogenerated PR by renovate bot")
```suggestion
	message ("PR autogenerated by dependabot")
```

2021-05-31 14:35 UTC, anisaoshafi commented on Dangerfile
> +
```suggestion
```

2021-05-31 14:57 UTC, anisaoshafi requested changes
Small comments

2021-05-31 14:57 UTC, anisaoshafi commented on Dangerfile
> +	fail "Please provide a valid PR title label: [Added/[Fixed]/[Changed]/[Removed]/[Security]/[Other]"
```suggestion
	fail "Please provide a valid PR title label: [Added]/[Fixed]/[Changed]/[Removed]/[Security]/[Other]"
```

2021-05-31 15:22 UTC, jaume-blv commented on Dangerfile
> +	fail "Please provide a valid PR title label: [Added/[Fixed]/[Changed]/[Removed]/[Security]/[Other]"
mmhhh nice, thanks

2021-05-31 15:30 UTC, anisaoshafi commented on Dangerfile
> +	fail "Please provide a valid Jira ticket ID associated to this PR: [BEL-XXXX]. If you do not have any associated Jira ticket, just use [BEL-XXXX] "
a nit pick:
```suggestion
	fail "Please provide a valid Jira ticket ID associated to this PR: [BEL-XXXX]. If you do not have any associated Jira ticket, just use [BEL-XXXX]"
```

2021-05-31 16:09 UTC, jaume-blv commented on Dangerfile
> +	fail "Please provide a valid Jira ticket ID associated to this PR: [BEL-XXXX]. If you do not have any associated Jira ticket, just use [BEL-XXXX] "
💋

2021-05-31 16:11 UTC, anisaoshafi approved these changes
lgtm 👍🏼

2021-06-01 14:51 UTC, gingrassia commented on Dangerfile
> +elsif !github.pr_title.match(/^\[.*\]\s?\[BEL-\d+\]/)
this is a public repo, which means people from outside Belvo can create PRs... so we will be forcing them to add this even when they don't have one. What should we do there?

2021-06-02 15:39 UTC, merged