Adding Typescript support for Node SDK
belvo-finance/belvo-js pull request #86
Opened 2021-06-09 14:02 UTC by renan-at-belvo

- Added Typescript as a dev-dependency package
- Added types for the Belvo API returns
- Added types for each endpoint (based on API Reference documentation)
- Set the noncompatbile resources on endpoints as private (for better Intellisense)
- Fixed some JSDoc types and comments
- Removed comment about encryptionKey parameter (deprecated)

2021-06-09 14:06 UTC, menecio commented on types/accounts.d.ts
> + * An Account is the representation of a bank account inside a financial institution.
this is repeated

2021-06-09 14:10 UTC, menecio commented on src/institutions.js
> +  resume() {}
Why do we need these? institutions only support listing and detail

2021-06-09 14:11 UTC, renan-at-belvo commented on types/accounts.d.ts
> + * An Account is the representation of a bank account inside a financial institution.
Generators bug. Fixing.

2021-06-09 14:14 UTC, renan-at-belvo commented on src/institutions.js
> +  resume() {}
Exactly for supporting only these resources. As we're extending the whole Resources class, Typescript Intellisense understands that Institutions class can access list, detail, resume and delete methods. Adding this @private with the methods for this endpoint, it will only display list and detail as supported methods for this class.

2021-06-09 14:22 UTC, renan-at-belvo commented on src/institutions.js
> +  resume() {}
<img width="392" alt="withPrivateMethods" src="https://user-images.githubusercontent.com/85626401/121372810-f1e86400-c914-11eb-8033-801c330eece2.png">
<img width="450" alt="withoutPrivateMethods" src="https://user-images.githubusercontent.com/85626401/121372822-f3b22780-c914-11eb-9c0a-9ac7b4893b28.png">

2021-06-09 14:52 UTC, renan-at-belvo commented on types/accounts.d.ts
> + * An Account is the representation of a bank account inside a financial institution.
@menecio already commited the fix for that one ;)

2021-06-16 07:24 UTC, menecio commented
@renan-at-belvo Be sure to run eslint, as the build is failing due to linting issues

2021-06-16 12:53 UTC, renan-at-belvo commented
> @renan-at-belvo Be sure to run eslint, as the build is failing due to linting issues

Just sent the fixes for eslint things.

2021-06-30 12:15 UTC, renan-at-belvo commented
Anything else @menecio for this to be ready?

2021-07-02 09:06 UTC, ioannisbelvo requested changes

2021-07-02 09:06 UTC, ioannisbelvo commented on src/taxReturns.js
> +   * @param {boolean} [options.attachPDF] - If `true`, you will receive the PDF as a binary string.
We have another options field now **type** which can be "**yearly**" or **monthly**

2021-07-02 14:45 UTC, renan-at-belvo commented on src/taxReturns.js
> +   * @param {boolean} [options.attachPDF] - If `true`, you will receive the PDF as a binary string.
Thanks @ioannisbelvo! Just send the PR supporting this new type param on taxReturns. 

Any else, please let me know.

2021-07-05 14:43 UTC, benitocas88 commented on types/belvo.d.ts
> +    session: APISession;
question, this morning this change was released => https://github.com/belvo-finance/belvo-js/blob/master/src/belvo.js#L19

How could affect here? @renan-at-belvo

2021-07-05 14:56 UTC, renan-at-belvo commented on types/belvo.d.ts
> +    session: APISession;
@benitocas88 I will add this URL treatment in my files too. So I can properly inform which value needs to be informed on this constructor.

2021-07-05 15:05 UTC, renan-at-belvo commented on types/belvo.d.ts
> +    session: APISession;
Already added the support for the urlResolver there, @benitocas88. If you need anything else, please let me know.

2021-07-08 22:55 UTC, benitocas88 approved these changes
Go ahead

2021-07-08 22:58 UTC, benitocas88 commented
Think you need sign your commit @renan-at-belvo 
you can find in notion like "Signing Commits"

2021-07-09 21:23 UTC, renan-at-belvo commented
Closing this pull request as it's giving Danger errors (and I need to GPG sign the commit too).

2021-07-09 21:23 UTC, closed without merging